jobs:
  build:
    docker:
      # The image used to build our project, build
      # your own using the Dockerfile provided below
      # and replace here. I put my own image here for
      # the example.
      - image: abronan/rust-circleci:latest

    environment:
      # Set your codecov token if your repository is private.
      CODECOV_TOKEN: 10f59a58-1b0c-40c1-a4d7-8e3e65c9ecf0
      TZ: "/usr/share/zoneinfo/US/Pacific"

    steps:
      - checkout
      - restore_cache:
          key: project-cache
      - run:
          name: Check formatting
          command: |
            rustfmt --version
            cargo fmt -- --write-mode=diff
      - run:
          name: Nightly Build
          command: |
            rustup run nightly rustc --version --verbose
            rustup run nightly cargo --version --verbose
            rustup run nightly cargo build
      - run:
          name: Stable Build
          command: |
            rustup run stable rustc --version --verbose
            rustup run stable cargo --version --verbose
            rustup run stable cargo build
      - run:
          name: Test
          command: rustup run stable cargo test
      - run:
          name: Upload Coverage
          command: ./scripts/codecov.sh
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"